### ISSUE TITLE
Deployment of new cluster

### ISSUE THREAD

**Issue by pandanos** [couchbasecloud/terraform-provider-couchbase-capella#211] opened 2024-07-28 21:26 UTC
**I have created API keys with permissions.**

**I am following the examples here:**
https://github.com/couchbasecloud/terraform-provider-couchbase-capella/tree/main/examples/cluster

**But i am getting this error:**

│ Error: Error creating cluster
│ 
│   with couchbase-capella_cluster.mno_cluster,
│   on cluster.tf line 38, in resource "couchbase-capella_cluster" "mno_cluster":
│   38: resource "couchbase-capella_cluster" "mno_cluster" {
│ 
│ There is an error during cluster creation. Please check in Capella to see if any hanging resources have been created, unexpected error: {"hint":"The request was malformed or invalid.","message":"Bad Request.
│ Error: body contains unknown key \"configurationType\".","code":1000,"httpStatusCode":400}

I have tried both with AWS, Azure and GCP and still no luck.
It works to create clusters in the console.

**Comment by l0n3star** [comment] 2024-08-04 01:30
@pandanos This is actually a known issue with the API server.  I will update when this is fixed.

**Comment by l0n3star** [comment] 2024-08-09 01:13
Hi @pandanos the issue is resolved.  API server was fixed by @PaulomeeCb

**Closed** 2024-08-09 01:13 UTC
